### ISSUE TITLE
get_image_front() timeout

### ISSUE THREAD

**Issue by sandor111** [ci-group/learning_machines_robobo#24]
I just can not get the get_image_front function to work it keeps timing out / giving this error.
![Screenshot_694](https://github.com/ci-group/learning_machines_robobo/assets/17690323/e4aec2f8-3f03-47bb-be30-af211b30d480)

**Comment by JJWRoeloffs** [comment]
I've been trying to recreate your issue, but I cannot on my own Windows machine with everything set as it is in the codebase right now.

Can you give me a (preferably minimal) setup that reproduces the issue from the ground. `get_image_front()` has been a part of `run_all_actions()` since the start of the course, so you have probably run it before, with it unexpectedly breaking because of some change.

**Comment by sandor111** [comment]
A minimal setup results in the same error, only changes I made are the following:
https://github.com/sandor111/learning_machines_robobo/commit/a387006ae7ff465f653a0ea762410c750d9dfc8b

Restarting docker temporarly solves the problem, it progressively comes back after running a few times.
![image](https://github.com/ci-group/learning_machines_robobo/assets/17690323/53c26a3e-84ff-42a1-8c1f-11870b77e908)
Right after restarting docker it was able to capture the image, so it seems like I can use the image but after a few times it crashes again. This makes training quite difficult, possibly it is some kind of memory leak in the setup?

**Comment by JJWRoeloffs** [comment]
I'm sorry, but I still cannot reproduce the issue (screenshot from own attempt, but just cloning your repo, installing CoppeliaSim, setting the IP adress in setup.bash and then runnning run.ps1 without modifications also works for me):

![image](https://github.com/ci-group/learning_machines_robobo/assets/99962354/934ccc24-30f0-43d3-8af4-f988f6c02a34)

There doesn't appear to be a memory leak anywhere, and I never go over 16 (out of 32) gigs ram used, even with 2000 instead of 500 saved images. (Also, memory leaks would be upstream issues, I haven't written any C++ myself.)

What is the system profile information when you're running it? Can you spot a high ram usage (Docker can easily use 10G or more, but anything over 20 is unexpected)? 

Can you try to update things, and re-try? Perhaps it's something with a specific patch of CoppeliaSim that was out when you downloaded it, or similar.

What are your system specifications: What windows build are you on, and what hardware do you have installed in your system?

**Comment by JJWRoeloffs** [comment]
I see, I see, that does indeed make sense. 8Gigs is too little to run python in docker on the already RAM-hungry Windows.
Running on other people's hardware is the right choice. Alternatively, there would have been space available to run on from the VU, I believe. I also know some other group is using a free-trial's worth of server compute to train on.
